# /**************************************************************************
#
#  This file is part of the Mishurov Finance website
#
#  Copyright (C) 2022 Alexander Mishurov
#
#  GNU General Public License Usage
#  This file may be used under the terms of the GNU
#  General Public License version 3. The licenses are as published by
#  the Free Software Foundation and appearing in the file LICENSE.GPL3
#  included in the packaging of this file. Please review the following
#  information to ensure the GNU General Public License requirements will
#  be met: https://www.gnu.org/licenses/gpl-3.0.html.
#
# **************************************************************************/

version: '3.9'

x-env: &oracle_env
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/oracle/client
  - DEBUG=true
  - LOCAL_DB=false
  - MEMCACHED=false

x-secrets: &django_secrets
  - credentials.json
  - cwallet.sso
  - tnsnames.ora

x-volumes: &django_volumes
  - ./finance:/app
  - oracle_client:/opt/oracle/client
  - ./configs/django.json:/etc/configs/django.json
  - ./configs/supervisord.conf:/etc/configs/supervisord.conf
  - ./configs/gunicorn.conf.py:/etc/configs/gunicorn.conf.py

services:
  app:
    container_name: finance_app
    image: registry.local:32000/finance_app:dev
    build:
      context: .
      target: dev
    command: /bin/bash -c 'sleep 1d'
    ports:
      - 8000:8000
    environment: *oracle_env
    volumes: *django_volumes
    secrets: *django_secrets
    depends_on:
      - es
      - memcached
      - pgbouncer
    networks:
      - finance_net_dev

  celery:
    container_name: finance_celery
    image: registry.local:32000/finance_app:dev
    command: /bin/bash -c 'supervisord -c /etc/configs/supervisord.conf'
    environment: *oracle_env
    volumes: *django_volumes
    secrets: *django_secrets
    depends_on:
      - redis
      - memcached
      - pgbouncer
    networks:
      - finance_net_dev

  redis:
    container_name: finance_redis
    image: docker.io/redis:7.0-bullseye
    networks:
      - finance_net_dev

  es:
    container_name: finance_elastic
    image: docker.io/elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
      - logger.level=WARN
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - finance_net_dev

  memcached:
    container_name: finance_memcached
    image: docker.io/memcached:1.6.15-bullseye
    command: memcached -m 128
    networks:
      - finance_net_dev

  pgbouncer:
    container_name: finance_pgbouncer
    image: docker.io/edoburu/pgbouncer:1.15.0
    secrets:
      - pgbouncer.ini
      - pg-users.txt
    depends_on:
      - db
    entrypoint: /usr/bin/pgbouncer
    command: /var/run/secrets/pgbouncer.ini
    networks:
      - finance_net_dev

  db:
    container_name: finance_db
    image: docker.io/postgres:14.2-bullseye
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - finance_net_dev

volumes:
  # https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html
  # instantclient-basiclite-linux.x64
  #
  # deployment/scripts/partials/create_volume.sh
  # cd oracle
  # docker volume create oracle_client
  # tar -C ./client -c -f- . | docker run --rm -i \
  #    -v oracle_client:/data alpine tar -C /data/ -xv -f-
  oracle_client:
    external: true
  es_data:
    driver: local

secrets:
  cwallet.sso:
    file: ./secrets/cwallet.sso
  tnsnames.ora:
    file: ./secrets/tnsnames.ora
  credentials.json:
    file: ./secrets/credentials.json
  pgbouncer.ini:
    file: ./secrets/pgbouncer.ini
  pg-users.txt:
    file: ./secrets/pg-users.txt

networks:
  finance_net_dev:
    name: finance_net_dev
