# /**************************************************************************
#
#  This file is part of the Mishurov Finance website
#
#  Copyright (C) 2022 Alexander Mishurov
#
#  GNU General Public License Usage
#  This file may be used under the terms of the GNU
#  General Public License version 3. The licenses are as published by
#  the Free Software Foundation and appearing in the file LICENSE.GPL3
#  included in the packaging of this file. Please review the following
#  information to ensure the GNU General Public License requirements will
#  be met: https://www.gnu.org/licenses/gpl-3.0.html.
#
# **************************************************************************/

apiVersion: v1
kind: Service
metadata:
  name: certbot
spec:
  selector:
    app: certbot
  ports:
    - port: 80
      targetPort: 80

---

# kubectl create secret generic certbot-secrets \
#   --from-file=../certbot/secrets/ -o yaml \
#   --dry-run=client > ./secrets/certbot-secrets.yml
# kubectl apply -f ./secrets/certbot-secrets.yml

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-cronjob
  labels:
    app: certbot
spec:
  schedule: '0 0 1 * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: secrets
              secret:
                secretName: certbot-secrets
          containers:
            - name: certbot
              image: registry.local:32000/finance_certbot:1.0
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 80
              command: ['bash']
              args: ['./renew.sh']
              volumeMounts:
                - name: secrets
                  mountPath: /var/run/secrets
                  readOnly: true
