# Generated by Django 3.2 on 2021-04-23 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200, verbose_name='ticker')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('exchange', models.CharField(blank=True, max_length=200, verbose_name='exchange')),
                ('currency', models.CharField(max_length=200, verbose_name='currency')),
                ('type', models.CharField(choices=[('B', 'Bond'), ('S', 'Stock')], max_length=1, verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'securities',
                'ordering': ['ticker'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_date', models.DateTimeField(verbose_name='fiscal date')),
                ('net_income', models.BigIntegerField(default=0, verbose_name='net income')),
                ('cost_of_revenue', models.BigIntegerField(default=0, verbose_name='cost of revenue')),
                ('total_revenue', models.BigIntegerField(default=0, verbose_name='total revenue')),
                ('gross_profit', models.BigIntegerField(default=0, verbose_name='gross profit')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_date', models.DateTimeField(verbose_name='fiscal date')),
                ('operating_cashflow', models.BigIntegerField(default=0, verbose_name='operating cashflow')),
                ('investing_cashflow', models.BigIntegerField(default=0, verbose_name='investing cashflow')),
                ('financing_cashflow', models.BigIntegerField(default=0, verbose_name='financing cashflow')),
                ('capital_expenditures', models.BigIntegerField(default=0, verbose_name='capital expenditures')),
                ('net_borrowings', models.BigIntegerField(default=0, verbose_name='net borrowings')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, verbose_name='type')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('open', models.FloatField(default=0, verbose_name='open')),
                ('close', models.FloatField(default=0, verbose_name='close')),
                ('high', models.FloatField(default=0, verbose_name='high')),
                ('low', models.FloatField(default=0, verbose_name='low')),
                ('volume', models.PositiveBigIntegerField(default=0, verbose_name='volume')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_date', models.DateTimeField(verbose_name='fiscal date')),
                ('total_assets', models.BigIntegerField(default=0, verbose_name='total assets')),
                ('total_liabilities', models.BigIntegerField(default=0, verbose_name='total liabilities')),
                ('total_stock_equity', models.BigIntegerField(default=0, verbose_name='total stock equity')),
                ('total_current_assets', models.BigIntegerField(default=0, verbose_name='total current assets')),
                ('total_current_liabilities', models.BigIntegerField(default=0, verbose_name='total current liabilities')),
                ('inventory', models.BigIntegerField(default=0, verbose_name='inventory')),
                ('cash', models.BigIntegerField(default=0, verbose_name='cash')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Activity Ratios'), ('L', 'Liquidity Ratios'), ('S', 'Solvency Ratios'), ('P', 'Profitability Ratios'), ('V', 'Valuation Ratios'), ('F', 'Free Cash Flows')], max_length=1, verbose_name='type')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('key', models.CharField(max_length=200, verbose_name='key')),
                ('primary_color1', models.CharField(default='steelblue', help_text="Firm's line chart color or area chart gradient 1", max_length=200, verbose_name='primary color 1')),
                ('primary_color2', models.CharField(default='royalblue', help_text="Firm's area chart gradient 2", max_length=200, verbose_name='primary color 2')),
                ('secondary_color', models.CharField(default='lightgray', help_text='Indstry average line chart color or tooltip color', max_length=200, verbose_name='secondary color')),
                ('visible', models.BooleanField(default=True, verbose_name='is visible')),
            ],
        ),
        migrations.CreateModel(
            name='BondOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('currency', models.CharField(max_length=200, verbose_name='currency')),
                ('last_price', models.FloatField(default=0, verbose_name='last price, %')),
                ('last_trade', models.DateTimeField(blank=True, null=True, verbose_name='last trade date')),
                ('maturity_date', models.DateTimeField(verbose_name='maturity date')),
                ('coupon_date', models.DateTimeField(blank=True, null=True, verbose_name='coupon date')),
                ('coupon_period', models.PositiveBigIntegerField(default=0, verbose_name='coupon period')),
                ('coupon_rate', models.FloatField(default=0, verbose_name='coupon rate, %')),
                ('coupon_value', models.FloatField(default=0, verbose_name='coupon value')),
                ('lot_size', models.PositiveBigIntegerField(default=0, verbose_name='lot size')),
                ('lot_value', models.FloatField(default=0, verbose_name='lot value')),
                ('issue_volume', models.PositiveBigIntegerField(default=0, verbose_name='issue volume')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1, verbose_name='type')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('expiration', models.DateTimeField(verbose_name='expiration date')),
                ('strike', models.FloatField(default=0, verbose_name='strike price')),
                ('last_price', models.FloatField(default=0, verbose_name='last contract price')),
                ('last_trade', models.DateTimeField(blank=True, null=True, verbose_name='last trade date')),
                ('implied_volatility', models.FloatField(default=0, verbose_name='implied volatility')),
                ('exists', models.BooleanField(default=True, verbose_name='exists')),
                ('volume', models.PositiveBigIntegerField(default=0, verbose_name='volume')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='key')),
                ('page', models.CharField(choices=[('H', 'Home'), ('E', 'Equity'), ('F', 'Fixed Income'), ('P', 'Portfolio Tools')], max_length=1, verbose_name='page')),
                ('text', models.TextField(blank=True, verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='FirmOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('sector', models.CharField(max_length=200, verbose_name='sector')),
                ('industry', models.CharField(max_length=200, verbose_name='industry')),
                ('shares_outstanding', models.PositiveBigIntegerField(verbose_name='shares outstanding')),
                ('book_value', models.FloatField(default=0, verbose_name='book value')),
                ('dividend_yield', models.FloatField(default=0, verbose_name='dividend yield')),
                ('eps', models.FloatField(default=0, verbose_name='eps')),
                ('ev_ebitda', models.FloatField(default=0, verbose_name='EV/EBITDA')),
                ('insider_ownership', models.FloatField(default=0, verbose_name='insider ownership, %')),
                ('institutional_ownership', models.FloatField(default=0, verbose_name='institutional ownership, %')),
                ('beta', models.FloatField(default=0, verbose_name='1-year beta')),
                ('week52_high', models.FloatField(default=0, verbose_name='52 week high')),
                ('week52_low', models.FloatField(default=0, verbose_name='52 week low')),
                ('short_ratio', models.FloatField(default=0, verbose_name='short ratio')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('is_snp', models.BooleanField(default=False, verbose_name='is in S&P500')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.security')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('ev', models.BigIntegerField(default=0, verbose_name='enterprise value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
